name = "performance"
logfile = ""
loglevel = "DEBUG"

localaddr = "localhost:8444"
externaladdr = "https://performance.sammlung.cc"
searchaddr = "https://performance.sammlung.cc"
detailaddr = "https://mediathek.hgk.fhnw.ch/performance"

templates = "/root/ink3web/data/web/performance/templates/"
staticfiles = "/root/ink3web/data/web/performance/static"
datadir = "/var/www/vhosts/performance.ausstellung.cc/digitalesee"

mediaserverbase = "https://ba14ns21403-sec1.fhnw.ch/mediasrv"
mediaserverkey = "sdfsdafsdfsdfsd"
mediaservertokenexp = "6h"

jwtkey = "iox6poi24ajoai36fjoaej2fe4aoij" # ":Xf/#|IKYrDsNi4]LN*o(W7;:"
jwtalg = "HS512"

fieldmapping.author = "[persons].name.keyword"

openaiapikey = "%%OPENAI_API_KEY%%"

basefilter = """
[
  {
    "existsTerm": {
      "field": "poster"
    }
  },
  {
    "boolTerm": {
      "field": "acl.content.keyword",
      "and": false,
      "values": [
        "global/guest"
      ]
    }
  }
]
"""


#[[auth]]
#user="performance"
#password="schweiz"

[login]
jwtkey = "iox6poi24ajoai36fjoaej2fe4aoij" # ":Xf/#|IKYrDsNi4]LN*o(W7;:"
jwtalg = ["HS256","HS384","HS512"]
linktokenexp = "1h"
#url = "https://intern.hgk.fhnw.ch/ango/shib/auth/localhost"
url = "https://intern.hgk.fhnw.ch/ango/oidc/auth/revcat"
issuer = "auth.hgk.fhnw.ch/revcat"



[[locations]]
group = "net/local"
networks = ["127.0.0.1/32", "::1/128"]

[[locations]]
group = "location/fhnw"
networks = ["10.0.0.0/8", "192.168.0.0/16", "147.86.0.0/16"]

[[locations]]
group = "net/fhnw"
networks = ["10.0.0.0/8", "192.168.0.0/16", "147.86.0.0/16"]

[[locations]]
group = "location/memoriav"
networks = ["62.2.199.158/32"]

[[locations]]
group = "net/bfh"
networks = ["147.87.0.0/16", "5.35.244.248/32", "213.200.195.102/32", "193.5.80.0/21", "2a07:6b40::/29", "2001:620:500::/48"]

[[locations]]
group = "net/tabeahome"
networks = ["212.51.149.28/32", "2a02:168:5608:0:c8b5:db0f:4ce6:f9d1/48"]


[revcat]
endpoint = "https://localhost:8443/graphql"
insecure = true
apikey = "%%TEST_APIKEY%%"
jwtkey = "%%REVCAT_JWTKEY%%"

[directus]
baseurl = "https://cms.basel-collections.ch"
token = "abc123"
cachetime = "10s"
catalogid = 2

[locale]
default = "de"
folder = ""
#folder = "rcfront/revcati13n"
available = ["de", "fr", "it", "en"]

[[collections]]
id = 1
identifier = "cat:\"zotero2!!PCB_Basel\""
title = "Performance Chronik Basel"
url = "https://www.performancechronikbasel.ch/"
image = "performance_chronik_klein.png"
contact = "Muda Mathis, Sabine Gebhardt Fink, Margarit von Büren"

[[collections]]
id = 5
identifier = "cat:\"zotero2!!ACT Performance Festival\""
title = "ACT"
url = "https://www.act-perform.net/"
image = "act_klein.png"
contact = "Marion Ritzmann, Hannah Weinberger"

#[[collections]]
#id = 10
#identifier = "cat:\"zotero2!!Performance Art!!6x2 Performance-Duos\""
#title = "6x2 Performance-Duos"
#url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/23"
#image = "6x2duos_klein.png"
#contact = "Pascale Grau, Claudia Grimm"

[[collections]]
id = 11
identifier = "cat:\"zotero2!!Archive des Ephemeren\""
title = "Archive des Ephemeren"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/12"
image = "archive_des_ephemeren_klein.png"
contact = "Pascale Grau, Margarit von Büren, PANCH"

[[collections]]
id = 27
identifier = "cat:\"zotero2!!Performance Art!!Together Elsewhere\""
title = "Together Elsewhere"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/26"
image = "together_elsewhere_klein.png"
contact = "Gisela Hochuli (PANCH), Pavana Reid (PAB)"

[[collections]]
id = 28
identifier = "cat:\"bangbang\""
title = "Revolving Histories"
url = "https://revolving-histories.ch/"
image = "revolving_histories_klein.png"
contact = "Sabine Gebhardt Fink, Muda Mathis, Chris Regn, Andrea Saemann, Margarit von Büren"

[[collections]]
id = 51
identifier = "cat:\"zotero2!!migma\""
title = "migma"
url = "https://www.migma.ch/ueber_migma.html"
image = "migma_klein.png"
contact = "Judith Huber"

[[collections]]
id = 55
identifier = "cat:\"zotero2!!Performance Art!!Doce en Diciembre\""
title = "Doce en Diciembre"
url = "https://mediathek.hgk.fhnw.ch/#/de/bestaende/25"
image = "doce_en_diciembre_klein.png"
contact = "Barbara Naegelin, Chris Regn, Andrea Saemann"

[[collections]]
id = 57
identifier = "cat:\"zotero2!!Dokumentation Archiv Performativ\""
title = "Dokumentation Archiv Performativ"
url = "http://archivperformativ.zhdk.ch/"
image = "interviews_archiv_performativ_klein.png"
contact = "Pascale Grau, Margarit von Büren"

[[collections]]
id = 59
identifier = "cat:\"zotero2!!Perf en Bref\""
title = "Perf En Bref"
url = "https://apresperf.ch/category/interviews"
image = "perf_en_bref_klein.png"
contact = "Chris Regn, Andrea Saemann"

[[collections]]
id = 60
identifier = "cat:\"zotero2!!Kaskadenkondensator Basel\""
title = "Kasko"
url = "https://www.kasko.ch/"
image = "kasko_klein.png"
contact = "Pascale Grau, Chris Regn"

[[collections]]
id = 61
identifier = "cat:\"zotero2!!Performance Art!!Must or Not\""
title = "Must or Not"
url = ""
image = "must_or_not_klein.png"
contact = "Andrea Saemann"

[[collections]]
id = 62
identifier = "cat:\"zotero2!!Performance Art!!Partout\""
title = "Partout"
url = ""
image = "partout_klein.png"
contact = "Andrea Saemann"

[[collections]]
id = 63
identifier = "cat:\"zotero2!!Monos\""
title = "Monos"
url = "https://mediathek.hgk.fhnw.ch/front/#/static/impressum-and-kontakt"
image = "monos_klein.png"
contact = "Tabea Lurk"

[[collections]]
id = 64
identifier = "cat:\"zotero2!!Konvolute\""
title = "Konvolute"
url = "https://mediathek.hgk.fhnw.ch/front/#/static/impressum-and-kontakt"
image = "konvolute_klein.png"
contact = "Tabea Lurk"

[[collections]]
id = 65
identifier = "cat:\"zotero2!!PPP-ProgrPerformancePlattform\""
title = "PPP-ProgrPerformancePlattform"
url = "https://mediathek.hgk.fhnw.ch/front/#/static/impressum-and-kontakt"
image = "ppp_klein.png"
contact = "Kate Burgener, Juerg Luedi"
